/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const clsx: typeof import('clsx')['clsx']
  const delay: typeof import('~/utils/delay')['delay']
  const range: typeof import('~/utils/range')['range']
}
